apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: year
  namespace: year
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

spec:
  ingressClassName: traefik
  rules:
    - host: year.andreybondarenko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: year
                port:
                  number: 3000
