---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-cli
  namespace: db
  labels:
    app.kubernetes.io/name: postgres-cli
    app.kubernetes.io/instance: postgres-cli
    app.kubernetes.io/managed-by: argoCD
spec:
  selector:
    matchLabels:
      app: postgres-cli
  template:
    metadata:
      labels:
        app: postgres-cli
    spec:
      containers:
        - name: postgres-cli
          image: harbor.andreybondarenko.com/library/postgres-cli:latest
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 64Mi
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: PGHOST
              value: "postgres-postgresql.db.svc.cluster.local"
            - name: PGUSER
              value: "postgres"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "ttrss"
            - name: OUTPUT_DIR
              value: "/data"
          volumeMounts:
            - name: data-export
              mountPath: "/data"
      volumes:
        - name: data-export
          persistentVolumeClaim:
            claimName: data-postgres-postgresql-0
