---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: matrix
  name: matrix
  labels:
    app: matrix
    tier: backend
    app.kubernetes.io/name: synapse
    app.kubernetes.io/instance: matrix
    app.kubernetes.io/managed-by: argo-cd
    app.kubernetes.io/part-of: matrix
    app.kubernetes.io/component: synapse
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: matrix
      tier: backend
  template:
    metadata:
      labels:
        app: matrix
        tier: backend
    spec:
      volumes:
        - name: matrix-lh
          persistentVolumeClaim:
            claimName: matrix-lh
        - name: synapse-config
          secret:
            secretName: config-synapse
            items:
              - key: config.yaml
                path: config.yaml
      containers:
        - name: synapse
          image: harbor.andreybondarenko.com/dockerhub/matrixdotorg/synapse:v1.147.1
          ports:
            - containerPort: 6167
              name: federation
            - containerPort: 8008
              name: metrics
          volumeMounts:
            - name: matrix-lh
              mountPath: /data
            - name: synapse-config
              mountPath: /data/config.yaml
              subPath: config.yaml
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: /data/config.yaml
          resources:
            requests:
              cpu: "10m"
              memory: "266Mi"
            limits:
              memory: "266Mi"
      initContainers:
        - name: fix-permissions
          image: harbor.andreybondarenko.com/dockerhub/busybox
          command: ["sh", "-c", "chown -R 991:991 /data"]
          volumeMounts:
            - name: matrix-lh
              mountPath: /data
