---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: clamav
  labels:
    app: clamav
    app.kubernetes.io/name: clamav
    app.kubernetes.io/instance: clamav
    app.kubernetes.io/part-of: clamav
    app.kubernetes.io/managed-by: argo-cd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      securityContext:
        runAsUser: 101
        runAsGroup: 103
        fsGroup: 103
      containers:
        - name: clamd
          image: harbor.andreybondarenko.com/library/clamav:latest
          ports:
            - containerPort: 3200
              name: api
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/clamav
              name: avdata
            - mountPath: /tmp
              name: tmp
            - mountPath: /etc/clamav/clamd.conf
              name: clamav
              subPath: clamd.conf
            - name: log
              mountPath: /var/log/clamav
          resources:
            requests:
              cpu: "10m"
              memory: "3300Mi"
            limits:
              memory: "3309Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
        - name: fresclam
          image: harbor.andreybondarenko.com/library/clamav:latest
          env:
            - name: UPDATE
              value: "true"
          volumeMounts:
            - mountPath: /var/lib/clamav
              name: avdata
            - mountPath: /etc/clamav/clamd.conf
              name: clamav
              subPath: clamd.conf
            - name: log
              mountPath: /var/log/clamav
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: "10m"
              memory: "1016Mi"
            limits:
              memory: "1016Mi"
        - name: exporter
          image: harbor.andreybondarenko.com/github/sergeymakinen/clamav_exporter:v2.1.2
          ports:
            - containerPort: 9906
              name: metrics
              protocol: TCP
          args:
            - "--clamav.address"
            - "tcp://localhost:3200"
          resources:
            requests:
              cpu: "10m"
              memory: "128Mi"
            limits:
              memory: "128Mi"
      volumes:
        - name: avdata
          persistentVolumeClaim:
            claimName: avdata
        - name: clamav
          configMap:
            name: clamav
            items:
              - key: clamd.conf
                path: clamd.conf
        - name: log
          emptyDir:
            sizeLimit: 100Mi
        - name: tmp
          emptyDir:
            sizeLimit: 600Mi
