apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: clamav-allow-ingress-mail-and-monitoring
  namespace: clamav
spec:
  podSelector:
    matchLabels:
      app: clamav
  policyTypes:
    - Ingress
  ingress:
    # Rspamd -> clamd
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: mail
      ports:
        - protocol: TCP
          port: 3200
    # Prometheus -> clamav exporter
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 9906
    # Nextcloud -> clamd
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: nextcloud
      ports:
        - protocol: TCP
          port: 3200
