apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: plex-allow-ingress-from-lan
  namespace: plex
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 192.168.1.0/24
      ports:
        - protocol: TCP
          port: 32400
        - protocol: UDP
          port: 1900
        - protocol: UDP
          port: 5353
        - protocol: TCP
          port: 8324
        - protocol: UDP
          port: 32410
        - protocol: UDP
          port: 32412
        - protocol: UDP
          port: 32413
        - protocol: UDP
          port: 32414
        - protocol: TCP
          port: 32469
