apiVersion: apps/v1
kind: Deployment
metadata:
  name: hister
  namespace: hister
  labels:
    app: hister
    app.kubernetes.io/instance: hister
    app.kubernetes.io/name: hister
    app.kubernetes.io/managed-by: argoCD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hister
  template:
    metadata:
      labels:
        app: hister
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: hister
          image: harbor.andreybondarenko.com/github/asciimoo/hister:v0.5.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          env:
            - name: HISTER__SERVER__ADDRESS
              value: 0.0.0.0:8081
            - name: HISTER__SERVER__BASE_URL
              value: https://hister.andreybondarenko.com/69f3c798b93a21c04299d7316d74fca32a5b5816e572f37c/
            - name: HISTER_DATA_DIR
              value: /data
          ports:
            - name: app
              containerPort: 8081
          volumeMounts:
            - name: hister-data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /
              port: app
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: app
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
        - name: nginx
          image: nginx:1.27.5-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          readinessProbe:
            httpGet:
              path: /69f3c798b93a21c04299d7316d74fca32a5b5816e572f37c/
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /69f3c798b93a21c04299d7316d74fca32a5b5816e572f37c/
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              memory: 128Mi
      volumes:
        - name: hister-data
          persistentVolumeClaim:
            claimName: hister-data
        - name: nginx-config
          configMap:
            name: hister-nginx
