apiVersion: apps/v1
kind: Deployment
metadata:
  name: hister
  namespace: hister
  labels:
    app: hister
    app.kubernetes.io/instance: hister
    app.kubernetes.io/name: hister
    app.kubernetes.io/managed-by: argoCD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hister
  template:
    metadata:
      labels:
        app: hister
    spec:
      enableServiceLinks: false
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: hister
          image: harbor.andreybondarenko.com/github/asciimoo/hister:v0.5.0
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 65532
            runAsGroup: 65532
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          env:
            - name: HISTER__SERVER__ADDRESS
              value: 0.0.0.0:8080
            - name: HISTER__SERVER__BASE_URL
              value: https://hister.andreybondarenko.com/
            - name: HISTER_DATA_DIR
              value: /data
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: hister-data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 256Mi
      volumes:
        - name: hister-data
          persistentVolumeClaim:
            claimName: hister-data
