---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-cli
  namespace: db
  labels:
    app.kubernetes.io/name: mysql-cli
    app.kubernetes.io/instance: mysql-cli
    app.kubernetes.io/managed-by: argoCD
spec:
  selector:
    matchLabels:
      app: mysql-cli
  template:
    metadata:
      labels:
        app: mysql-cli
    spec:
      containers:
        - name: mysql-cli
          image: harbor.andreybondarenko.com/library/mysql-cli:latest
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 64Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
            - name: MYSQLHOST
              value: "mysql.db.svc.cluster.local"
