---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: db
  labels:
    app: mysql
    tier: mysql
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argoCD
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
      tier: mysql
  template:
    metadata:
      labels:
        app: mysql
        tier: mysql
    spec:
      containers:
        - image: harbor.andreybondarenko.com/dockerhub/mysql:8.0.41
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          readinessProbe:
            tcpSocket:
              port: 3306
          resources:
            requests:
              cpu: "18m"
              memory: "1600Mi"
            limits:
              memory: "1600Mi"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
        - name: mysqld-exporter
          image: harbor.andreybondarenko.com/quay/prometheus/mysqld-exporter:main
          command:
            - /bin/sh
            - -ec
            - |
              cat > /tmp/.my.cnf <<EOF
              [client]
              user = root
              password = ${MYSQL_ROOT_PASSWORD}
              host = 127.0.0.1
              EOF
              exec /bin/mysqld_exporter --config.my-cnf=/tmp/.my.cnf
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 9104
              name: mysqld-exporter
          resources:
            requests:
              memory: "100Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-lh
