apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
---
apiVersion: v1
kind: Service
metadata:
  name: ha-external
  namespace: homeassistant
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: 8123
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: ha-external-manual
  namespace: homeassistant
  labels:
    kubernetes.io/service-name: ha-external
    endpointslice.kubernetes.io/managed-by: homeassistant-manual
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 8123
endpoints:
  - addresses:
      - 192.168.1.247
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hsts
  namespace: homeassistant
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: homeassistant
  name: ha-andreybondarenko
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: homeassistant-hsts@kubernetescrd
  labels:
    app: homeassistant
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/instance: homeassistant
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argoCD
spec:
  ingressClassName: traefik
  rules:
    - host: ha.andreybondarenko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ha-external
                port:
                  number: 8123
