apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
---
apiVersion: v1
kind: Service
metadata:
  name: ha-external
  namespace: homeassistant
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8123
      targetPort: 8123
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ha-external
  namespace: homeassistant
subsets:
  - addresses:
      - ip: 192.168.1.247
    ports:
      - name: http
        port: 8123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: homeassistant
  name: ha-andreybondarenko
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
  labels:
    app: homeassistant
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/instance: homeassistant
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argoCD
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ha.andreybondarenko.com
      secretName: ha-andreybondarenko-tls
  rules:
    - host: ha.andreybondarenko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ha-external
                port:
                  number: 8123
