apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: homeassistant
  name: ha-andreybondarenko
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: homeassistant-hsts@kubernetescrd
  labels:
    app: homeassistant
    app.kubernetes.io/name: homeassistant
    app.kubernetes.io/instance: homeassistant
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argoCD
spec:
  ingressClassName: traefik
  rules:
    - host: ha.andreybondarenko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ha-external
                port:
                  number: 8123
