apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: traefik-allow-egress-homeassistant-external
  namespace: traefik
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    # Home Assistant external endpoint behind service homeassistant/ha-external.
    - to:
        - ipBlock:
            cidr: 192.168.1.247/32
      ports:
        - protocol: TCP
          port: 8123
