apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: external-secrets-allow-ingress-webhook
  namespace: external-secrets
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: external-secrets-webhook
  policyTypes:
    - Ingress
  ingress:
    # Admission webhook calls can come from API server/control-plane addresses.
    - from:
        - ipBlock:
            cidr: 192.168.1.209/32
      ports:
        - protocol: TCP
          port: 10250
    - from:
        - ipBlock:
            cidr: 192.168.1.100/32
      ports:
        - protocol: TCP
          port: 10250
