apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ui
  namespace: nextcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: nextcloud-hsts@kubernetescrd
spec:
  rules:
    - host: cloud.andreybondarenko.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-nextcloud
                port:
                  number: 80
