apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-uploads
  namespace: nextcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.middlewares: nextcloud-chain@kubernetescrd
spec:
  rules:
    - host: cloud.andreybondarenko.com
      http:
        paths:
          - path: /remote.php/dav
            pathType: Prefix
            backend:
              service:
                name: nginx-nextcloud
                port:
                  number: 80
