apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-report-ui
  namespace: ca-scanner
  labels:
    app.kubernetes.io/name: ca-report-ui
    app.kubernetes.io/instance: ca-report-ui
    app.kubernetes.io/managed-by: argoCD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca-report-ui
  template:
    metadata:
      labels:
        app: ca-report-ui
    spec:
      serviceAccountName: ca-scanner
      containers:
        - name: ui
          image: harbor.andreybondarenko.com/library/canitiser:latest
          command: ["python", "/app/ca-report-server.py"]
          env:
            # use "all" to show all namespaces, or "ca-scanner" to show only that ns
            - name: REPORT_NAMESPACE
              value: "ca-scanner"
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ca-report-ui
  namespace: ca-scanner
spec:
  selector:
    app: ca-report-ui
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
