---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 3.3.0
    chart: eck-operator
    helm:
      releaseName: eck-operator
      values: |
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            memory: 1Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: elastic-system
  syncPolicy:
    automated: {}
