---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: collabora
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://collaboraonline.github.io/online/'
    targetRevision: 1.1.57
    chart: collabora-online
    helm:
      values: |
        collabora:
          server_name: office.andreybondarenko.com
          extra_params: --o:ssl.enable=false --o:ssl.termination=true -o:security.enable_metrics_unauthenticated=true
        resources:
          requests:
            cpu: "171m"
            memory: "1015Mi"
          limits:
            memory: "1015Mi"
        autoscaling:
          enabled: false
        image:
          repository: harbor.andreybondarenko.com/dockerhub/collabora/code
          pullSecrets:
            - name: my-image-registry
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: collabora
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
