---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-adapter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 5.3.0
    chart: prometheus-adapter
    helm:
      releaseName: my-adapter
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated: {}
