---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ot-container-kit.github.io/helm-charts/
    targetRevision: 0.16.6
    chart: redis
    helm:
      releaseName: redis
      parameters:
      - name: redisExporter.enabled
        value: 'true'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wordpress
  syncPolicy:
    automated: {}
