---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elastic-stack-network-policy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/shaman007/home-k3s.git"
    path: elastic
    targetRevision: HEAD
    directory:
      recurse: false
      include: network-policy-*.yaml
      exclude: network-policy-*mastodon*.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: elastic-stack
  syncPolicy:
    automated: {}
