---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hister
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shaman007/home-k3s.git'
    path: hister
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: hister
  syncPolicy:
    automated: {}
