DEPRECATED - Using Bitnami chart for Vault is deprecated, it's no more maintained.
 Please use the  official HashiCorp chart
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.31.0
    helm:
      parameters:
        - name: injector.enabled
          value: 'false'
        - name: server.ha.enabled
          value: 'true'
        - name: server.ha.raft.enabled
          value: 'true'
        - name: server.ha.replicas
          value: '2'
    chart: vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
