---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dawarich
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/shaman007/home-k3s.git'
    path: dawarich
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dawarich
  ignoreDifferences:
  - group: ""
    kind: PersistentVolumeClaim
    jsonPointers:
    - /spec/resources/requests/storage
  syncPolicy:
    automated: {}
    syncOptions:
    - RespectIgnoreDifferences=true
