---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/shaman007/home-k3s.git"
    path: homeassistant
    targetRevision: HEAD
    directory:
      recurse: false
      include: "*.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homeassistant
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
