---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ot-container-kit.github.io/helm-charts/
    targetRevision: 0.23.0
    chart: redis-operator
    helm:
      releaseName: redis-operator
      values: |
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            memory: 500Mi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ot-operators
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - ServerSideApply=true
