---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-custom
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/shaman007/home-k3s.git"
    path: harbor
    targetRevision: HEAD
    directory:
      recurse: false
      include: "*-*.yaml"
      exclude: network-policy-*.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: harbor
  syncPolicy:
    automated: {}
