---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wordpress
  name: php
  labels:
    app: wordpress
    tier: backend
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress
    app.kubernetes.io/managed-by: argoCD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: backend
  template:
    metadata:
      labels:
        app: wordpress
        tier: backend
    spec:
      securityContext:
        runAsUser: 33
        runAsGroup: 33
        fsGroup: 33
      volumes:
        - name: phpini
          configMap:
            name: php-fpm-config
        - name: wordpress-lh
          persistentVolumeClaim:
            claimName: wordpress-lh
        - name: varrun
          emptyDir:
            sizeLimit: 10Mi
        - name: run
          emptyDir:
            sizeLimit: 10Mi
        - name: tmp
          emptyDir:
            sizeLimit: 1000Mi
      containers:
        - name: php
          image: harbor.andreybondarenko.com/library/php:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: phpini
              mountPath: /etc/php/8.4/fpm/pool.d/php.ini
              subPath: php.ini
            - name: phpini
              mountPath: /etc/php/8.4/fpm/php.ini
              subPath: php.ini
            - name: phpini
              mountPath: /etc/php/8.4/fpm/pool.d/www.conf
              subPath: www.conf
            - name: wordpress-lh
              mountPath: /code
            - name: varrun
              mountPath: /var/run/php
            - name: run
              mountPath: /run
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: "66m"
              memory: "768Mi"
            limits:
              memory: "768Mi"
