apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wordpress-allow-ingress-to-mysql-wordpress-from-php
  namespace: wordpress
spec:
  podSelector:
    matchLabels:
      app: mysql-wordpress
      tier: mysql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: wordpress
              tier: backend
      ports:
        - protocol: TCP
          port: 3306
