---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cli
  namespace: redis
  labels:
    app.kubernetes.io/name: redis-cli
    app.kubernetes.io/instance: redis-cli
    app.kubernetes.io/managed-by: argoCD
spec:
  selector:
    matchLabels:
      app: redis-cli
  template:
    metadata:
      labels:
        app: redis-cli
    spec:
      containers:
        - name: redis-cli
          image: harbor.andreybondarenko.com/library/redis-cli:latest
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: password
            - name: REDIS_HOST
              value: "redis-master.redis.svc.cluster.local"
            - name: OUTPUT_DIR
              value: "/data"
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 64Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: backup-lh
