---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: minecraft
  name: minecraft
  labels:
    tier: backend
    app: minecraft
    app.kubernetes.io/name: minecraft
    app.kubernetes.io/instance: minecraft
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: argoCD
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
      tier: backend
  template:
    metadata:
      labels:
        app: minecraft
        tier: backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: minecraft-lh
          persistentVolumeClaim:
            claimName: minecraft1-lh
        - name: tmp
          emptyDir:
            sizeLimit: 100Mi
      containers:
        - name: mnecraft
          image: harbor.andreybondarenko.com/dockerhub/itzg/minecraft-server:2026.2.1
          env:
            - name: EULA
              value: "TRUE"
            - name: ENABLE_RCON
              value: "TRUE"
            - name: TYPE
              value: CUSTOM
            - name: CUSTOM_SERVER
              value: "/data/server.jar"
            - name: CREATE_CONSOLE_IN_PIPE
              value: "TRUE"
            - name: RCON_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: password
                  key: password
          ports:
            - containerPort: 25565
            - containerPort: 25575
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: minecraft-lh
              mountPath: /data
            - mountPath: /tmp
              name: tmp
          resources:
            requests:
              cpu: "1235m"
              memory: "1990Mi"
            limits:
              memory: "1990Mi"
