apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: convertx-allow-ingress-intra-namespace
  namespace: convertx
spec:
  podSelector:
    matchLabels:
      app: convertx
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: convertx
      ports:
        - protocol: TCP
          port: 3000
