---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store-gateway
  namespace: monitoring
  labels:
    app: thanos-store-gateway
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store-gateway
  template:
    metadata:
      labels:
        app: thanos-store-gateway
        thanos-store-api: "true"
    spec:
      initContainers:
        - name: volume-mount-hack
          image: harbor.andreybondarenko.com/dockerhub/busybox
          command: ["sh", "-c", "chown -R 1001:1001 /data"]
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: thanos
          image: harbor.andreybondarenko.com/quay/thanos/thanos:v0.41.0
          args:
            - "store"
            - "--log.level=info"
            - "--data-dir=/data"
            - "--objstore.config-file=/etc/thanos/objstore.yml"
            - "--index-cache-size=500MB"
            - "--chunk-pool-size=500MB"
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          resources:
            requests:
              cpu: "10m"
              memory: "2288Mi"
            limits:
              memory: "2288Mi"
          livenessProbe:
            httpGet:
              port: 10902
              path: /-/healthy
          readinessProbe:
            httpGet:
              port: 10902
              path: /-/ready
          volumeMounts:
            - name: objstoreyml
              mountPath: /etc/thanos/
            - name: data
              mountPath: /data/
      volumes:
        - name: objstoreyml
          secret:
            secretName: thanos-objstore-secret
        - name: data
          persistentVolumeClaim:
            claimName: storagegw-lh
