---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-compactor
  namespace: monitoring
  labels:
    app: thanos-compactor
    app.kubernetes.io/name: thanos-compactor
    app.kubernetes.io/instance: thanos-compactor
    app.kubernetes.io/managed-by: argoCD
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: thanos-compactor
  template:
    metadata:
      labels:
        app: thanos-compactor
        thanos-store-api: "true"
    spec:
      initContainers:
        - name: volume-mount-hack
          image: harbor.andreybondarenko.com/dockerhub/busybox:1.37
          command: ["sh", "-c", "chown -R 1001:1001 /data"]
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 32Mi
      containers:
        - name: thanos
          image: harbor.andreybondarenko.com/quay/thanos/thanos:v0.41.0
          args:
            - "compact"
            - "--log.level=info"
            - "--data-dir=/data"
            - "--objstore.config-file=/etc/thanos/objstore.yml"
            - --retention.resolution-raw=14d
            - --retention.resolution-5m=30d
            - --retention.resolution-1h=10950d
            - --delete-delay=24h
            - "--wait"
          ports:
            - name: http
              containerPort: 10902
            - name: grpc
              containerPort: 10901
          livenessProbe:
            httpGet:
              port: 10902
              path: /-/healthy
          readinessProbe:
            httpGet:
              port: 10902
              path: /-/ready
          volumeMounts:
            - name: objstoreyml
              mountPath: /etc/thanos/
            - name: data
              mountPath: /data/
          resources:
            requests:
              cpu: "10m"
              memory: "2291Mi"
            limits:
              memory: "2291Mi"
      volumes:
        - name: objstoreyml
          secret:
            secretName: thanos-objstore-secret
        - name: data
          persistentVolumeClaim:
            claimName: compactor-lh
